### ISSUE TITLE
有没有可能支持一下非请求结构体的方法作为handle的场景？

### ISSUE THREAD

**Issue by trim21** [long2ice/fibers#3]
在v2看到帖子想尝试一下，然后发现按照readme的例子的话，所有的路由都必须用一个结构体接收请求信息，然后用结构体的一个方法作为实际的路由。

但我的handler已经定义成了结构体的一个方法（`Handler{log,cache,metrics...}.GetUser(*fiber.Ctx) error`)，我的log等等基础组件都绑在这个结构体上，也不可能移到别的地方去。这样一来就没办法跟这个库一起使用。

有没有可能支持一下？

**Comment by trim21** [comment]
大概尝试了一下用reflect和泛型实现了一个比较简略的版本。如果进一步实现的话可以还考虑支持结构体读取多个信息，支持TextUnmarshaler等等。不过要达到fastapi那样依赖注入的易用程度可能比较难。

（也可以考虑给handler添加一个返回值用来声明返回类型，不过这就跟fiber原本的风格比较冲突了）

https://gist.github.com/Trim21/a3994fcd182f4d4f936738f5acb86559


```golang

...

type Req struct {
	ID int `params:"id"`

	Q int `query:"q"`
	J int `query:"j"`
	K int `query:"k"`

	Token string `header:"x-auth"`
}

func main() {
	app := fiber.New()

	app.Get("/:id", Wrap(func(c *fiber.Ctx, req Req) error {
		return c.JSON(req)
	}))
}

// Wrap
// the `F` type param is for future (maybe) go compile inline
func Wrap[T any, F func(c *fiber.Ctx, req T) error](h F) fiber.Handler {
...

```

例子里这个req如果是纯手写convert的话约300ns/op，`Wrap`之后约500ns/op，基本不影响性能。

**Comment by long2ice** [comment]
不使用结构体的话感觉没有什么好的方法可以注入请求参数

**Comment by trim21** [comment]
> 不使用结构体的话感觉没有什么好的方法可以注入请求参数

我给了个例子（

**Comment by long2ice** [comment]
你试试最新代码

**Comment by trim21** [comment]
看起来好像挺 OK，我试试
